// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddUserDialog: typeof import('./components/addUserDialog.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    Layout: typeof import('./components/Layout.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    Pagination: typeof import('./components/Pagination.vue')['default']
    ProblemListBaseInfo: typeof import('./components/ProblemListBaseInfo.vue')['default']
    ProblemListHistory: typeof import('./components/ProblemListHistory.vue')['default']
    StatusDialog: typeof import('./components/StatusDialog.vue')['default']
  }
}

export { }
